/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LivreurRouteRouteImport } from './routes/livreur/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LivreurIndexRouteImport } from './routes/livreur/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as LivreurStockRouteImport } from './routes/livreur/stock'
import { Route as LivreurProfilRouteImport } from './routes/livreur/profil'
import { Route as LivreurLivraisonsRouteImport } from './routes/livreur/livraisons'
import { Route as LivreurBadgeRouteImport } from './routes/livreur/badge'
import { Route as AdminStockRouteImport } from './routes/admin/stock'
import { Route as AdminPaieRouteImport } from './routes/admin/paie'
import { Route as AdminLivreursRouteImport } from './routes/admin/livreurs'
import { Route as AdminLivraisonsRouteImport } from './routes/admin/livraisons'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LivreurRouteRoute = LivreurRouteRouteImport.update({
  id: '/livreur',
  path: '/livreur',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LivreurIndexRoute = LivreurIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LivreurRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const LivreurStockRoute = LivreurStockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => LivreurRouteRoute,
} as any)
const LivreurProfilRoute = LivreurProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => LivreurRouteRoute,
} as any)
const LivreurLivraisonsRoute = LivreurLivraisonsRouteImport.update({
  id: '/livraisons',
  path: '/livraisons',
  getParentRoute: () => LivreurRouteRoute,
} as any)
const LivreurBadgeRoute = LivreurBadgeRouteImport.update({
  id: '/badge',
  path: '/badge',
  getParentRoute: () => LivreurRouteRoute,
} as any)
const AdminStockRoute = AdminStockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPaieRoute = AdminPaieRouteImport.update({
  id: '/paie',
  path: '/paie',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLivreursRoute = AdminLivreursRouteImport.update({
  id: '/livreurs',
  path: '/livreurs',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLivraisonsRoute = AdminLivraisonsRouteImport.update({
  id: '/livraisons',
  path: '/livraisons',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/livreur': typeof LivreurRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/livraisons': typeof AdminLivraisonsRoute
  '/admin/livreurs': typeof AdminLivreursRoute
  '/admin/paie': typeof AdminPaieRoute
  '/admin/stock': typeof AdminStockRoute
  '/livreur/badge': typeof LivreurBadgeRoute
  '/livreur/livraisons': typeof LivreurLivraisonsRoute
  '/livreur/profil': typeof LivreurProfilRoute
  '/livreur/stock': typeof LivreurStockRoute
  '/admin/': typeof AdminIndexRoute
  '/livreur/': typeof LivreurIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/livraisons': typeof AdminLivraisonsRoute
  '/admin/livreurs': typeof AdminLivreursRoute
  '/admin/paie': typeof AdminPaieRoute
  '/admin/stock': typeof AdminStockRoute
  '/livreur/badge': typeof LivreurBadgeRoute
  '/livreur/livraisons': typeof LivreurLivraisonsRoute
  '/livreur/profil': typeof LivreurProfilRoute
  '/livreur/stock': typeof LivreurStockRoute
  '/admin': typeof AdminIndexRoute
  '/livreur': typeof LivreurIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/livreur': typeof LivreurRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/livraisons': typeof AdminLivraisonsRoute
  '/admin/livreurs': typeof AdminLivreursRoute
  '/admin/paie': typeof AdminPaieRoute
  '/admin/stock': typeof AdminStockRoute
  '/livreur/badge': typeof LivreurBadgeRoute
  '/livreur/livraisons': typeof LivreurLivraisonsRoute
  '/livreur/profil': typeof LivreurProfilRoute
  '/livreur/stock': typeof LivreurStockRoute
  '/admin/': typeof AdminIndexRoute
  '/livreur/': typeof LivreurIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/livreur'
    | '/login'
    | '/register'
    | '/admin/livraisons'
    | '/admin/livreurs'
    | '/admin/paie'
    | '/admin/stock'
    | '/livreur/badge'
    | '/livreur/livraisons'
    | '/livreur/profil'
    | '/livreur/stock'
    | '/admin/'
    | '/livreur/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/admin/livraisons'
    | '/admin/livreurs'
    | '/admin/paie'
    | '/admin/stock'
    | '/livreur/badge'
    | '/livreur/livraisons'
    | '/livreur/profil'
    | '/livreur/stock'
    | '/admin'
    | '/livreur'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/livreur'
    | '/login'
    | '/register'
    | '/admin/livraisons'
    | '/admin/livreurs'
    | '/admin/paie'
    | '/admin/stock'
    | '/livreur/badge'
    | '/livreur/livraisons'
    | '/livreur/profil'
    | '/livreur/stock'
    | '/admin/'
    | '/livreur/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  LivreurRouteRoute: typeof LivreurRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/livreur': {
      id: '/livreur'
      path: '/livreur'
      fullPath: '/livreur'
      preLoaderRoute: typeof LivreurRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/livreur/': {
      id: '/livreur/'
      path: '/'
      fullPath: '/livreur/'
      preLoaderRoute: typeof LivreurIndexRouteImport
      parentRoute: typeof LivreurRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/livreur/stock': {
      id: '/livreur/stock'
      path: '/stock'
      fullPath: '/livreur/stock'
      preLoaderRoute: typeof LivreurStockRouteImport
      parentRoute: typeof LivreurRouteRoute
    }
    '/livreur/profil': {
      id: '/livreur/profil'
      path: '/profil'
      fullPath: '/livreur/profil'
      preLoaderRoute: typeof LivreurProfilRouteImport
      parentRoute: typeof LivreurRouteRoute
    }
    '/livreur/livraisons': {
      id: '/livreur/livraisons'
      path: '/livraisons'
      fullPath: '/livreur/livraisons'
      preLoaderRoute: typeof LivreurLivraisonsRouteImport
      parentRoute: typeof LivreurRouteRoute
    }
    '/livreur/badge': {
      id: '/livreur/badge'
      path: '/badge'
      fullPath: '/livreur/badge'
      preLoaderRoute: typeof LivreurBadgeRouteImport
      parentRoute: typeof LivreurRouteRoute
    }
    '/admin/stock': {
      id: '/admin/stock'
      path: '/stock'
      fullPath: '/admin/stock'
      preLoaderRoute: typeof AdminStockRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/paie': {
      id: '/admin/paie'
      path: '/paie'
      fullPath: '/admin/paie'
      preLoaderRoute: typeof AdminPaieRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/livreurs': {
      id: '/admin/livreurs'
      path: '/livreurs'
      fullPath: '/admin/livreurs'
      preLoaderRoute: typeof AdminLivreursRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/livraisons': {
      id: '/admin/livraisons'
      path: '/livraisons'
      fullPath: '/admin/livraisons'
      preLoaderRoute: typeof AdminLivraisonsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminLivraisonsRoute: typeof AdminLivraisonsRoute
  AdminLivreursRoute: typeof AdminLivreursRoute
  AdminPaieRoute: typeof AdminPaieRoute
  AdminStockRoute: typeof AdminStockRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminLivraisonsRoute: AdminLivraisonsRoute,
  AdminLivreursRoute: AdminLivreursRoute,
  AdminPaieRoute: AdminPaieRoute,
  AdminStockRoute: AdminStockRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface LivreurRouteRouteChildren {
  LivreurBadgeRoute: typeof LivreurBadgeRoute
  LivreurLivraisonsRoute: typeof LivreurLivraisonsRoute
  LivreurProfilRoute: typeof LivreurProfilRoute
  LivreurStockRoute: typeof LivreurStockRoute
  LivreurIndexRoute: typeof LivreurIndexRoute
}

const LivreurRouteRouteChildren: LivreurRouteRouteChildren = {
  LivreurBadgeRoute: LivreurBadgeRoute,
  LivreurLivraisonsRoute: LivreurLivraisonsRoute,
  LivreurProfilRoute: LivreurProfilRoute,
  LivreurStockRoute: LivreurStockRoute,
  LivreurIndexRoute: LivreurIndexRoute,
}

const LivreurRouteRouteWithChildren = LivreurRouteRoute._addFileChildren(
  LivreurRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  LivreurRouteRoute: LivreurRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
